### ISSUE TITLE
Alpha 2 Checklist

### ISSUE THREAD

**Issue by Lemmmy** [Lemmmy/JRogue#14]
- [ ] Spells
- [ ] Ranged weapons
- [ ] Potions
- [ ] Larger levels
- [ ] Some level decoration
- [ ] Ice and hell
- [ ] More humanoid monsters with magic and ranged attacks

**Comment by Lignumm** [comment]
Alright, let's work out who does what. I call dibs on ranged weps & potions.

**Comment by Lemmmy** [comment]
Larger levels are a one-commit change so that's easy
